"""prereg_freeze.py — Hash-lock a charter / PR-FAQ / pre-registration artifact.

The agent or user runs this once per artifact when the artifact is final.
After freezing, the agent treats the artifact as append-only — any change
requires a deviation entry in `decisions.md`.

Per CHARTER C5 / D-8 (`.rebuild/CHARTER.md`) and the references:
- references/rd/rd_charter.md § Freezing the charter
- references/pure_research/prfaq.md § Freezing the PR/FAQ
- references/pure_research/preregistration.md § Freezing the pre-registration

Usage:
    python scripts/prereg_freeze.py --type charter --path charter.md
    python scripts/prereg_freeze.py --type prfaq --path prfaq.md
    python scripts/prereg_freeze.py --type prereg --id PR_001 \\
        --path prereg/PR_001.md

Outputs:
    Writes <project_root>/prereg/<name>.lock containing:
        artifact_type: charter | prfaq | prereg
        artifact_path: <relative path to artifact>
        sha256: <hex digest of artifact content>
        frozen_at: <UTC ISO timestamp>

Exit codes:
    0: frozen successfully
    1: artifact path not found
    2: invalid arguments (e.g., --id missing for prereg)
    3: lock already exists with mismatching hash
       (use deviation entry instead of re-freezing)
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

ARTIFACT_TYPES = ("charter", "prfaq", "prereg")
CHUNK = 65536


def compute_sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(CHUNK), b""):
            h.update(chunk)
    return h.hexdigest()


def parse_lock(path: Path) -> dict[str, str]:
    """Parse an existing lock file into a dict."""
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if ":" in s:
            k, _, v = s.partition(":")
            out[k.strip()] = v.strip()
    return out


def freeze(
    artifact_type: Literal["charter", "prfaq", "prereg"],
    path: Path,
    prereg_id: str | None,
) -> dict[str, str]:
    if artifact_type not in ARTIFACT_TYPES:
        raise ValueError(f"--type must be one of {ARTIFACT_TYPES}, got {artifact_type}")
    if not path.exists():
        raise FileNotFoundError(f"artifact not found: {path}")

    if artifact_type == "prereg":
        if not prereg_id:
            raise ValueError("--id is required when --type=prereg")
        # Project root is parent of prereg/
        project_root = path.resolve().parent.parent
        lock_name = f"{prereg_id}.lock"
    else:
        project_root = path.resolve().parent
        lock_name = f"{artifact_type}.lock"

    lock_dir = project_root / "prereg"
    lock_dir.mkdir(parents=True, exist_ok=True)
    lock_path = lock_dir / lock_name

    sha = compute_sha256(path)

    # If lock exists, compare. Same hash = idempotent. Different hash = error.
    if lock_path.exists():
        existing = parse_lock(lock_path)
        existing_sha = existing.get("sha256", "")
        if existing_sha == sha:
            return {
                "artifact_type": artifact_type,
                "artifact_path": str(path),
                "sha256": sha,
                "frozen_at": existing.get("frozen_at", "unknown"),
                "lock_path": str(lock_path),
                "status": "already_frozen_idempotent",
            }
        raise RuntimeError(
            f"Lock {lock_path} already exists with sha256 {existing_sha[:16]}..., "
            f"but current artifact hash is {sha[:16]}... . "
            "This means the artifact was edited after freezing. "
            "Do not re-freeze; file a deviation entry in decisions.md instead."
        )

    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    rel_path = path.resolve().relative_to(project_root) if path.resolve().is_relative_to(project_root) else path
    content = (
        f"# {artifact_type} freeze lock — generated by scripts/prereg_freeze.py\n"
        f"artifact_type: {artifact_type}\n"
        f"artifact_path: {rel_path}\n"
        f"sha256: {sha}\n"
        f"frozen_at: {timestamp}\n"
    )
    lock_path.write_text(content, encoding="utf-8")

    return {
        "artifact_type": artifact_type,
        "artifact_path": str(rel_path),
        "sha256": sha,
        "frozen_at": timestamp,
        "lock_path": str(lock_path),
        "status": "frozen",
    }


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--type", required=True, choices=ARTIFACT_TYPES)
    p.add_argument("--path", required=True, type=Path)
    p.add_argument("--id", default=None, help="prereg ID (e.g., PR_001), required when --type=prereg")
    args = p.parse_args()

    try:
        result = freeze(args.type, args.path, args.id)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(2)
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(3)

    print(f"{result['status']}: {result['artifact_type']} -> {result['lock_path']}")
    print(f"  sha256:    {result['sha256']}")
    print(f"  frozen_at: {result['frozen_at']}")
    print()
    print("Next: append a state-transition entry to decisions.md naming this freeze.")


if __name__ == "__main__":
    main()
